Repository containers/storage, pull requests merged in 2024-01, with the labels that each got.

#1791 Move minimal golang to v1.20
  .cirrus.yml
  go.mod
Labels: approved, lgtm

#1780 graphtest: skip tests on insufficient permissions
  drivers/graphtest/graphtest_unix.go
Labels: approved, lgtm

#1793 homedir: drop check for ConfigHome mode
  pkg/homedir/homedir_unix.go
Labels: approved, lgtm

#1794 chunked: validate converted images
  cmd/containers-storage/diff.go
  pkg/chunked/storage_linux.go
  pkg/chunked/storage_unsupported.go
Labels: approved, lgtm

#1798 [release-1.46] [crio-1.27] Cherry-pick changes from containers/storage/pull#1641
  layers.go
Labels: kind/bug, lgtm

#1797 [release-1.46] [crio-1.26] Cherry-pick changes from containers/storage/pull#1641
  layers.go
Labels: kind/bug, lgtm

#1795 [release-1.37] [crio-1.24] Cherry-pick changes from containers/storage/pull#1641
  layers.go
Labels: lgtm

#1800 fix: "undefined: quota.BackingFsBlockDeviceLink" on non-cgo build
  drivers/quota/projectquota.go
  drivers/quota/projectquota_supported.go
Labels: approved, lgtm

#1799 overlay: use the default mode for the root directory
  drivers/driver.go
  drivers/overlay/overlay.go
  pkg/chunked/storage_linux.go
Labels: approved, lgtm

#1803 Bump to v1.52.0 and then 1.52.1-dev
  VERSION
Labels: approved, lgtm

#1804 overlay: move the fs-verity measurement to the chunked package
  drivers/driver.go
  drivers/overlay/composefs.go
  drivers/overlay/overlay.go
  pkg/chunked/storage_linux.go
  pkg/fsverity/fsverity_linux.go
  pkg/fsverity/fsverity_unsupported.go
Labels: approved

#1806 composefs: some fixes
  pkg/chunked/dump/dump.go
  pkg/chunked/storage_linux.go
Labels: approved

#1807 Store: add ImageDirectory() and ImageRunDirectory()
  cmd/containers-storage/image.go
  docs/containers-storage-get-image-dir.md
  docs/containers-storage-get-image-run-dir.md
  store.go
  tests/image-dirs.bats
Labels: approved, lgtm

#1812 homedir: use containers/storage on Windows
  pkg/homedir/homedir_windows.go
Labels: approved, lgtm

#1809 Run codespell on code
  Makefile
  idset_test.go
Labels: approved, lgtm

#1813 chunked: store UncompressedDigest if validated
  pkg/chunked/storage_linux.go
Labels: approved, lgtm
