Repository containers/storage, pull requests merged in 2024-09, with the labels that each got.

#2083 overlay: ignore EINVAL for cleanup unmount
  drivers/overlay/overlay.go
Labels: approved, lgtm

#2080 Be clearer about the layer store locking rules
  drivers/overlay/overlay.go
  layers.go
  store.go
Labels: approved, lgtm

#2079 Be explicit about impact of not writing caches
  pkg/chunked/cache_linux.go
Labels: approved, lgtm

#2088 Improve comments based on after-merge review comments
  drivers/overlay/overlay.go
  pkg/chunked/cache_linux.go
Labels: approved, lgtm

#2097 pkg/directory: correctly ignore ENOENT while walking
  pkg/directory/directory_unix.go
  pkg/directory/directory_windows.go
Labels: approved, lgtm

#2103 Switch to github.com/moby/sys/capability
  go.mod
  go.sum
  pkg/chrootarchive/chroot_linux.go
  pkg/unshare/unshare_linux.go
  vendor/github.com/moby/sys/capability/.codespellrc
  vendor/github.com/moby/sys/capability/.golangci.yml
  vendor/github.com/moby/sys/capability/CHANGELOG.md
  vendor/github.com/moby/sys/capability/LICENSE
  vendor/github.com/moby/sys/capability/README.md
  vendor/github.com/moby/sys/capability/capability.go
  vendor/github.com/moby/sys/capability/capability_linux.go
  vendor/github.com/moby/sys/capability/capability_noop.go
  vendor/github.com/moby/sys/capability/enum.go
  vendor/github.com/moby/sys/capability/enum_gen.go
  vendor/github.com/moby/sys/capability/syscall_linux.go
  vendor/modules.txt
Labels: approved, lgtm

#2100 Use strings.Cut{,Prefix,Suffix} where appropriate
  check.go
  cmd/containers-storage/copy.go
  drivers/overlay/mount.go
  drivers/windows/windows.go
  internal/opts/opts.go
  internal/opts/parse.go
  pkg/archive/archive_linux.go
  pkg/archive/changes.go
  pkg/archive/fflags_bsd.go
  pkg/mflag/flag.go
  pkg/mount/flags.go
  pkg/mount/mounter_freebsd.go
  pkg/mount/mounter_linux_test.go
  pkg/parsers/kernel/kernel_darwin.go
  pkg/parsers/operatingsystem/operatingsystem_linux.go
  pkg/parsers/parsers.go
  types/options.go
Labels: approved, lgtm

#2109 userns: skip "nogroup"
  userns.go
  userns_test.go
Labels: approved, lgtm, do-not-merge/hold

#2107 overlay: refactor getStagingDir helper
  drivers/overlay/overlay.go
Labels: approved, lgtm

#2102 Assorted nits reported by revive linter
  pkg/lockfile/lockfile.go
  pkg/unshare/unshare_test.go
Labels: approved, lgtm

#2112 overlay: fallback without data only layers
  drivers/overlay/overlay.go
Labels: approved, lgtm, area/composefs

#2116 Use tar-split/tar/asm.IterateHeaders now that it has been accepted
  pkg/chunked/compression_linux.go
  pkg/chunked/tar_split_linux.go
  pkg/chunked/tar_split_linux_test.go
Labels: approved, lgtm

#2119 chunked: ignore ErrLayerUnknown when creating cache
  pkg/chunked/cache_linux.go
Labels: approved, lgtm
