Repository containers/storage, pull requests merged in 2024-10, with the labels that each got.

#2118 chunked: define error for partial pulls not available
  pkg/chunked/storage.go
  pkg/chunked/storage_linux.go
Labels: approved, lgtm

#2125 Audit and update OWNERS file
  OWNERS
Labels: approved, lgtm

#2121 CI: Fix `git-validation.sh`
  hack/git-validation.sh
Labels: approved, lgtm

#2122 Fix copy/clone of empty value
  containers.go
  images.go
  layers.go
  store.go
Labels: approved, lgtm

#2129 Fix assignment of quota project IDs
  drivers/quota/projectquota_supported.go
Labels: approved, lgtm

#2133 chunked: prevent using an empty cache
  pkg/chunked/cache_linux.go
Labels: approved, lgtm

#2134 Use securejoin.SecureJoin when forming userns paths
  userns.go
  userns_test.go
  userns_unsupported.go
Labels: approved, lgtm

#2135 [release-1.55] backport fix for CVE-2026-9676
  .cirrus.yml
  userns.go
  userns_test.go
  userns_unsupported.go
Labels: approved, lgtm

#2130 Correctly compute UncompressedSize on zstd:chunked pull, don’t set it on estargz
  drivers/driver.go
  layers.go
  pkg/chunked/compression_linux.go
  pkg/chunked/compression_linux_test.go
  pkg/chunked/storage_linux.go
  store.go
Labels: kind/bug, approved, lgtm

#2136 Follow-ups to #2130
  layers.go
  pkg/chunked/storage_linux.go
Labels: approved

#2137 ci: add codespell
  .cirrus.yml
  .codespellrc
  Makefile
  pkg/chunked/cache_linux.go
  pkg/idtools/idtools.go
Labels: approved, lgtm

#2139 Bump the version to v1.55.1
  VERSION
Labels: approved, lgtm

#2145 composefs: use mount from file where supported
  drivers/overlay/composefs.go
Labels: approved, lgtm

#2147 fsdiff: mount both layers are read-only
  drivers/fsdiff.go
Labels: approved, lgtm

#2146 [release-1.51] Backport CVE-2024-9676 fix
  .cirrus.yml
  userns.go
  userns_test.go
  userns_unsupported.go
Labels: approved, lgtm

#2148 overlay: use private directory for composefs mounts
  drivers/overlay/composefs.go
  drivers/overlay/overlay.go
Labels: approved, lgtm

#2150 [release-1.51] Bump version to v1.51.2
  VERSION
Labels: approved, lgtm, ¯\_(ツ)_/¯

#2128 Refactor copy of slices and maps
  containers.go
  images.go
  layers.go
  store.go
Labels: approved, lgtm

#2153 overlay: make error lowercase
  drivers/overlay/overlay.go
Labels: approved, lgtm
