Repository containers/storage, pull requests merged in 2024-02, with the labels that each got.

#1817 Switch from libcontainer users package to moby/sys/user
  go.mod
  go.sum
  pkg/idtools/idtools_unix.go
  userns.go
  vendor/github.com/moby/sys/user/LICENSE
  vendor/github.com/moby/sys/user/lookup_unix.go
  vendor/github.com/moby/sys/user/user.go
  vendor/github.com/moby/sys/user/user_fuzzer.go
  vendor/github.com/opencontainers/runc/NOTICE
  vendor/modules.txt
Labels: approved, lgtm

#1824 overlay: fix build of composefs without cgo
  drivers/overlay/overlay_nocgo.go
Labels: approved, lgtm

#1825 chunked: report TOCDigest for converted layers
  pkg/chunked/storage_linux.go
Labels: approved

#1830 Extend PutLayer to optimize reusing data from existing layers
  layers.go
  store.go
Labels: approved, lgtm

#1832 Fix compilation on non-Linux
  pkg/fsverity/fsverity_unsupported.go
Labels: approved, lgtm

#1826 store: new API ApplyStagedLayer
  drivers/driver.go
  drivers/overlay/overlay.go
  layers.go
  store.go
  userns.go
Labels: approved, lgtm

#1833 storage: enable partial images by default
  docs/containers-storage.conf.5.md
  pkg/chunked/storage_linux.go
  storage.conf
Labels: approved, lgtm

#1834 Fix missing newline from stdout of create-container command
  cmd/containers-storage/create.go
Labels: approved, lgtm

#1840 overlay: drop FHGFSFs from network file systems
  drivers/overlay/.#overlay.go
  drivers/overlay/overlay.go
Labels: approved, lgtm

#1835 Synchronise documentation for convert_images flag
  docs/containers-storage.conf.5.md
  storage.conf
Labels: approved, lgtm

#1842 overlay: delete backup file
  drivers/overlay/.#overlay.go
Labels: approved, lgtm

#1844 Chunked cleanups
  layers.go
  pkg/chunked/compression_linux.go
  pkg/chunked/toc/toc.go
Labels: approved, lgtm

#1828 overlay: ignore chown errors in additionalimagestore
  drivers/overlay/overlay.go
Labels: approved, lgtm, 5.0

#1845 chunked: preserve the original value for symlinks
  pkg/chunked/storage_linux.go
Labels: approved, lgtm

#1843 chunked: add chunk size to cache file
  pkg/chunked/cache_linux.go
  pkg/chunked/cache_linux_test.go
Labels: approved, lgtm, 5.0

#1848 Revert commit that breaks podman backwards compatibility
  drivers/overlay/overlay.go
Labels: approved

#1847 Stop putting `user.overlay.*` into container layer
  pkg/archive/archive.go
Labels: approved, lgtm
